### ISSUE TITLE
Different boundary strings crash

### ISSUE THREAD

**Issue by slokhorst** [qqilihq/partial-emlx-converter#10]
While trying to convert a Mail/V3 inbox:

```
partial-emlx-converter INBOX.mbox/E511469D-DF47-4B2F-A77E-B6611C8680B2/ eml/
Converting [========--------------------------------] 20% 511.1s Data/1/6/Messages/61439.emlx(node:72447) UnhandledPromiseRejectionWarning: Error: Different boundary strings (expected '----=_NextPart_7ae48436ccb4c946256817a6c56cb01c', got: '----=_NextPart_7ae48436ccb4c946256817a6c56cb01c_alt')
    at parts.forEach.part (/usr/local/lib/node_modules/partial-emlx-converter/dist/converter.js:87:19)
    at Array.forEach (<anonymous>)
    at writeBody (/usr/local/lib/node_modules/partial-emlx-converter/dist/converter.js:80:11)
    at /usr/local/lib/node_modules/partial-emlx-converter/dist/converter.js:61:13
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/partial-emlx-converter/dist/converter.js:5:58)
(node:72447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have included [Data/1/6/Messages/61439.emlx](https://github.com/qqilihq/partial-emlx-converter/files/3126510/61439.emlx.txt) (with some data replaced with REDACTED, I haven't touched the part names/headers). Note that it doesn't contain anything like `_NextPart_7ae48436ccb4c946256817a6c56cb01c` or the `_alt` variant. Please let me know if there's some other file I can include to help diagnose the problem.

Edit: I think this is the relevant emlx instead: [11507.emlx](https://github.com/qqilihq/partial-emlx-converter/files/3126569/11507.emlx.txt)

**Comment by slokhorst** [comment]
At least, would it be possible to make this error non-fatal, i.e. skip this email but continue processing the other emails?

**Comment by qqilihq** [comment]
Yes, that makes sense. Would you be willing to contribute a PR?

**Comment by slokhorst** [comment]
See #11. This "bug" is not a big deal since only 1 out of 30,000 emails failed.
