### ISSUE TITLE
TypeError: Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by n9yty** [qqilihq/partial-emlx-converter#12]
Was hoping this would work, moved to a new computer and the import/Catalina/something broke and a lot of my old email archive mailboxes only show blank message windows. I tried to rebuild and it broke it worse. I have a copy of the pre-migration mailboxes, but doing an import in Mail on them only brings in avery small percentage.

Anyway, I am getting the error 'TypeError: Cannot read property 'readFile' of undefined' for each emlx file in the folder when i try this on a 10.15.2 system.

**Comment by qqilihq** [comment]
Make sure to use a NodeJS version which has `fs.promises` as stated in the [`readme.md`](https://github.com/qqilihq/partial-emlx-converter#build):

> Use a current version of Node.js (currently built and tested with v10.15.3 LTS). Install the dependencies, run the tests, and compile the TypeScript code with yarn or npm:

If that doesn't solve the issue, please post a working example which allows to reproduce this.
