### ISSUE TITLE
Non-Unicode encoding of message to convert

### ISSUE THREAD

**Issue by bgvoisin** [qqilihq/partial-emlx-converter#17]
First, a lot of thanks for your question at [https://apple.stackexchange.com/questions/312942/recovering-emails-from-defunct-imap-account](https://apple.stackexchange.com/questions/312942/recovering-emails-from-defunct-imap-account), showing the problem I was experiencing today was real, and for this solution. This works great, and was a life-saver. A suggestion maybe: in the installation instructions, it might be worth mentioning, for the non-programmer, that you need to cd to the uncompressed directory partial-emlx-converter-master first, and use sudo with npm.

I met an issue with one message, which had been forwarded to me twice the same day, by a Mac user using Mail and a Windows user using Thunderbird. The message included accented (French) characters. The version forwarded by the Mac user looked perfectly fine after applying your script; it turns out it was UTF-8, namely the forwarded content started with

> --Apple-Mail=_F89F0554-9AC4-4DD0-8186-2C5ED0B9DB79
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Type: TEXT/PLAIN;
	charset=utf-8

and was followed by UTF-8 text. The version forwarded by the Windows user had all accents mixed up after applying the script (see the attached screenshot, first version left, second version right); it was Windows Latin 1, namely the forwarded content started with

>--------------9195395EF01B76400F9EFD5B
Content-Transfer-Encoding: 8BIT
Content-Type: TEXT/PLAIN;
	charset=windows-1252;
	format=flowed

and was followed by Windows Latin 1 text. My impression is that the script read the message source as UTF-8 instead of Windows Latin 1.

The problem was finally solved by opening both the original .partial.emlx file and the converted .eml file in a text editor, making sure both were opened as Windows Latin 1, then pasting the message body from the original file to the converted file, saving the result as Windows Latin 1.

![Capture d’écran 2020-11-20 à 17 34 40](https://user-images.githubusercontent.com/23072783/99838186-0166b200-2b69-11eb-90de-ea98e82e5a6a.png)

**Comment by qqilihq** [comment]
Hi there,

thanks for the feedback, and good to hear you found it useful.

If you could provide a test file (or even a test case, or even a fix), that would be very appreciated :-)

**Comment by bgvoisin** [comment]
> Le 20 nov. 2020 à 20:11, Philipp Katz <notifications@github.com> a écrit :
> 
> If you could provide a test file (or even a test case, or even a fix), that would be very appreciated :-)

The problem is that the messages with which I observed this are not meant to be made public (internal emails of a research government agency). I'm not experienced with GitHub. Is there a way to send this test file to you directly, without the attachment showing up on the GitHub site?

I may try to create a message exhibiting the same problem, but it may take some time.

**Comment by qqilihq** [comment]
No worries -- if you get time for it once, it would be great :-)

Otherwise you can also send it to me directly via email to philipp@philippkatz.de. I am currently rather overloaded with other projects, so this will not be a fast fix, but I’ll definitely put it on the backlog!

**Comment by qqilihq** [comment]
Update: Have received the files via email and remove my email address from above’s post. Thanks, @bgvoisin !

**Comment by qqilihq** [comment]
Finally, I just had the opportunity to try this with the test data, and it seems like changing from `utf8` to `ascii` when reading the file fixes this:

https://github.com/qqilihq/partial-emlx-converter/blob/b2e471f107d0a2e60932eb2d6f3eba1a10cfd673/src/converter.ts#L58

For the test data, this does not have any negative side-effects, and the more I think about it, it `ascii` probably makes much more sense (see e.g. [here](https://stackoverflow.com/questions/1750387/what-is-the-encoding-of-an-eml-file-from-iiss-smtp-server) and [here](https://en.wikipedia.org/wiki/Unicode_and_email))

I’ll have another look during the next days.

**Comment by qqilihq** [comment]
Update: Above “solution” is obviously too simple, d'oh! :-)

I found this as a potential alternative for the current eml-format parser? I seems to be very well-suited for modifying an existing mail structure in a streaming way: https://www.npmjs.com/package/mailsplit

**Comment by qqilihq** [comment]
This is now fixed in the new 3.0.0 version which turned out to become a major rewrite from the initial version :-)

Thanks again @bgvoisin for the feedback!
