### ISSUE TITLE
Add paypal/donate link to the README

### ISSUE THREAD

**Issue by johncolby** [qqilihq/partial-emlx-converter#18]
I scoured the web off and on for 6 months for a tool to save my huge backed up email archive (whose IMAP is now offline) from death at the hands of Apple's nonstandard format. Just when I was about give up (and attempt to hack together something myself and probably fail) I found your partial-emlx-converter. PLEASE let us buy you a drink!

**Comment by qqilihq** [comment]
Glad to hear that it’s not only useful to me! :-) If you want to buy me a virtual drink, here’s my PayPal link: paypal.me/PhilippKatz (I’ll add this to the repo start page as well).

Cheers 🍻

**Comment by qqilihq** [comment]
THANK YOU, @johncolby !
