### ISSUE TITLE
Conversion starts but fails after a while with node V8.10 ubuntu

### ISSUE THREAD

**Issue by johnqube** [qqilihq/partial-emlx-converter#2]
Hello

while converting I hit this error

`Processing Messages/10752.emlx
(node:644) UnhandledPromiseRejectionWarning: Error: Different boundary strings
    at parts.forEach.part (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:76:19)
    at Array.forEach (<anonymous>)
    at writeBody (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:69:11)
    at parts.forEach.part (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:88:13)
    at Array.forEach (<anonymous>)
    at writeBody (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:69:11)
    at emlformat.parse (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:52:17)
    at Object.emlformat.parse (/home/qube/Téléchargements/partial-emlx-converter/node_modules/eml-format/lib/eml-format.js:554:5)
    at Promise (/home/qube/Téléchargements/partial-emlx-converter/build/src/converter.js:45:19)
    at new Promise (<anonymous>)
(node:644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
qube@ipv4:~/Téléchargements/partial-emlx-converter/build/src$ 
`
I hope it helps, thank you

**Comment by qqilihq** [comment]
Thank you for the info. The error in general states, that the file was not in the format as expected by the script. Any chance you can attach a (probably anonymized) sample file for testing?

**Comment by johnqube** [comment]
I also noticed there might be problems with missing attachment files, making the whole process crash if one single file is missing.

`node converter.js ~/Téléchargements/Mail2/Mail/V5/15
4E9E1F-D7BA-49A9-AA33-D6FCF6241149/INBOX.mbox/2FB7F392-FBE9-4E13-85D0-A6F07D9B94D4/ ~/Téléchargements/Mail2-out/inProcessing Data/0/4/Messages/40000.partial.emlx
Processing Data/0/4/Messages/40001.partial.emlx
(node:2791) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/qube/Téléchargements/Mail2/Mail/V5/154E9E1F-D7BA-49A9-AA33-D6FCF6241149/INBOX.mbox/2FB7F392-FBE9-4E13-85D0-A6F07D9B94D4/Data/0/4/Attachments/40001/2/Trame compte-rendu conseil de classe 2016.02.02.docx'`

as the file is

**Comment by johnqube** [comment]
There as well might be problems with spaces or special characters in path as this one is present but the scripts fails to find it

`Error: ENOENT: no such file or directory, open '/home/qube/Téléchargements/Mail2/Mail/V5/154E9E1F-D7BA-49A9-AA33-D6FCF6241149/INBOX.mbox/OUTBOX.mbox/2FB7F392-FBE9-4E13-85D0-A6F07D9B94D4/Data/0/5/Attachments/50431/2.6/éléments de réflexion pour bilan adulte.doc'
` 
as this particular file is definitely present but fails to find it

**Comment by johnqube** [comment]
[errormail.zip](https://github.com/qqilihq/partial-emlx-converter/files/2824454/errormail.zip)

there you are please delete me

**Comment by qqilihq** [comment]
Thanks, I'll have a look when I've some free time. Please delete the test file so that I can re-open the issue.

**Comment by qqilihq** [comment]
I could reproduce and fix the issue mentioned in your first post, thanks for the test file.

Regarding your follow-ups:

> I also noticed there might be problems with missing attachment files, making the whole process crash if one single file is missing.

This is somewhat by design. In the archive which I needed to convert, all files were supposed to be present.

> There as well might be problems with spaces or special characters in path as this one is present but the scripts fails to find it

I tried this locally with spaces and special characters (umlauts, accents), but could not reproduce this (running on macOS).
