### ISSUE TITLE
Attachment hunt may fail on large folders?

### ISSUE THREAD

**Issue by stucka** [qqilihq/partial-emlx-converter#31]
I believe I'm seeing a problem where attachments seem to fail for a folder structure with more than 100,000 emails, but not for ones with fewer.

My Node skills are awful, but I'm wondering if this is related to how the search for the attachment folders works, e.g., maybe it's looking in Data/1/1/Attachments while it should be looking in Data/1/1/1/Attachments or something along those lines.

Other conversions were successful, and I'm most grateful!

**Comment by qqilihq** [comment]
Hi stucka,

thank you for the feedback. The email archives which I have been processing with this tool have probably been 1-2 magnitudes smaller, but I do not see any obvious bottle neck in the current implementation. Also, finding the attachments should only work in a very narrow scope.

Could you provide some more details about the error you encountered? Did it crash? Was there an error message? If you still have them, any more details would be helpful.

Anyways, happy to hear that it helped :-)
